config/routes.rb
Osc::Application.routes.draw do
  resources :statuses

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessons#destroy', as: 'signout'

  get "author_sessions/controller"

  get "author_sessions/new"

  get "tags/index"

  get "tags/show"

  get "welcome/index"
  match 'home' => 'welcome#index' #added to allow page shortcuts
  match 'index' => 'welcome#index'

  get "welcome/getstarted"
  match 'getstarted' => 'welcome#getstarted'

  get "welcome/whatson"
  match 'whatson' => 'welcome#whatson'

  get "welcome/aboutus"
  match 'aboutus' => 'welcome#aboutus'

  get "welcome/race"
  match 'race' => 'welcome#race'

  get "welcome/gallery"
  match 'gallery' => 'welcome#gallery'

  get "welcome/joinus"
  match 'joinus' => 'welcome#joinus'

  get "welcome/access"

  get "welcome/login"

  resources :events

  resources :articles

  resources :comments

  resources :tags

  resources :authors

  resources :author_sessions,
            only: [ :new, :create, :destroy]
            
  match 'login' => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oval Ski Club</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= yield :head %> <!-- brings in head from other templates -->
</head>
  <body>    
    <!-- MAIN MENU -->
    <div class="navbar navbar-fixed-top" >            <!-- '-inverse' for a different coloured menu -->
      <div class="navbar-inner" style="padding-left:70px; ">
        <div class="container">
          <div class="row">

          <!-- ../../ allows images and links to work across the site where as ../ did not work on th edit pages -->
          <div ID="logo" Class="span2">
            <a class="brand" href="../../welcome/index.html" accesskey="H">
            <img src="../../assets/logo.png" height="20px" width="130" alt="Oval Ski Club"></a>
          </div>
          <div class="span8">
              <ul class="nav" style="margin-top: 0px;">
                <li><a href="../../welcome/getstarted.html" accesskey="1">Get Started</a></li>
                <li><a href="../../welcome/aboutus.html" accesskey="2">About Us</a></li>
                <li><a href="../../articles/" accesskey="3">News</a></li>              
                <li><a href="../../events/" accesskey="4">Whats on</a></li>
                <li><a href="../../welcome/race.html" accesskey="5">Race</a></li>
                <li><a href="../../welcome/gallery.html" accesskey="6">Gallery</a></li>
                <li><a href="../../welcome/joinus.html" accesskey="7">Join Us</a></li>      
              </ul>  
            </div>
            <!-- Login -->
            <div class="span2 pull-right">
              <!-- if logged in standard -->
                <% if logged_in? %>
                  <ul class="nav" style="margin-top: 0px;">
                    <li><%= link_to raw('Logout'), logout_path %></li>
                  </ul>
                <% else %>
              <!-- if logged in with facebook -->
                <% if active_user %>
                  Signed in as <strong><%= active_user.name %></strong>
                  <ul class="nav" style="margin-top: 0px;">
                    <li><%= link_to raw('Logout'), signout_path, id: "sign_out" %></li>
                  </ul>
                <% else %> 
              <!-- if not logged in -->
                  <ul class="nav" style="margin-top: 0px;">
                    <li><%= link_to raw('Login'), login_path %></li>
                  </ul>
                <% end %>                
              <% end %>
            </div>
            
            <!--end Login -->         
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <!-- END MAIN MENU -->

    <div class="container">
      <!-- Row of columns -->
      <div class="row">        
        <div class="span12">
        	<%= yield %>
        </div>
      </div>

      <br><br>
      <hr>
      <footer>
        <div class="row">
          <div class="span7">
            <p>&copy; Oval Ski Club 2013 |  <a href="access.html" accesskey="K"> Access Keys</a></p>
          </div>

          <div class="pull-right">
            <%= link_to image_tag('feed-icon-28x28.png'), articles_url(format: :atom)%>       
            <a href="http://www.facebook.com/group.php?gid=2256597544" target="_blank" accesskey="G"> <img src="../../assets/facebook.png" height="30" width="30" alt="Facebook"/></a>
            <a href="http://www.twitter.com" target="_blank" accesskey="T"> <img src="../../assets/twitter.png" height="30" width="30" alt="Twitter"/></a>
            <!--<a class="btn btn-mini"  href="#"><i class="icon-chevron-up"></i> To the top.</a> -->
          </div>
        </div>

        <!-- To the top! -->
        <div id="toTop" ><i class="icon-chevron-up"></i></div>

      </footer>

    </div>     <!-- /container -->

        <!-- The javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster 
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap-transition.js"></script>
    <script src="assets/js/bootstrap-alert.js"></script>
    <script src="assets/js/bootstrap-modal.js"></script>
    <script src="assets/js/bootstrap-dropdown.js"></script>
    <script src="assets/js/bootstrap-scrollspy.js"></script>
    <script src="assets/js/bootstrap-tab.js"></script>
    <script src="assets/js/bootstrap-tooltip.js"></script>
    <script src="assets/js/bootstrap-popover.js"></script>
    <script src="assets/js/bootstrap-button.js"></script>
    <script src="assets/js/bootstrap-collapse.js"></script>
    <script src="assets/js/bootstrap-carousel.js"></script>
    <script src="assets/js/bootstrap-typeahead.js"></script> -->

  </body>
</html>